### ISSUE TITLE
Documents used for fine-tuning the LLMs cyclicly? 

### ISSUE THREAD

**Issue by haizhou-shi** [Agentic-Learning-AI-Lab/anticipatory-recovery-public#1]
Hi, thanks for sharing the code of this intriguing paper! 

I am wondering do you have the document list described in Section 2 "Training Setup"? 

Thanks in advance!

**Comment by yanlai00** [comment]
The dataset we used is the CNN/Dailymail news dataset on huggingface: https://huggingface.co/datasets/cnn_dailymail/viewer/3.0.0

The 25 documents used in the experiment is randomly sampled for each run.

We plan to include experiments on other datasets in a future update to the paper.

**Comment by haizhou-shi** [comment]
Thank you so much for your timely response! 

For now, I am a bit curious about the 25 randomly sampled documents, and by taking a look at them, try to interpret this intriguing behavior of anticipatory recovery by taking. Do you have any suggestions on this issue? 

Best,

**Comment by yanlai00** [comment]
In the code there is a line to decode and visualize the sampled documents - you can apply it to every sample: https://github.com/Agentic-Learning-AI-Lab/anticipatory-recovery-public/blob/main/llm-memory/training/train_interleave.py#L275
